env:
  browser: true
  es6: true
extends:
  - "plugin:react/recommended"
  - airbnb
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
rules: { react/jsx-props-no-spreading: 0 }
